import streamlit as st
import requests
from bs4 import BeautifulSoup
from newspaper import Article
from dotenv import load_dotenv
import os
import textwrap
from datetime import datetime

load_dotenv()

# ========================= CONFIG =========================
API_KEY = os.getenv("XAI_API_KEY")
if not API_KEY:
    st.error("⚠️ Add your XAI_API_KEY to .env")
    st.stop()

API_URL = "https://api.x.ai/v1/chat/completions"
MODEL = "grok-4"           # Latest and best as of Nov 2025
# MODEL = "grok-4-1106"    # Uncomment if you have access (even stronger reasoning)

# Fix newspaper3k lxml issue
os.environ['NEWSPAPER_CLEANER'] = '0'

# ========================= UI =========================
st.set_page_config(page_title="Grok Truth Mirror", layout="centered", page_icon="🪞")
st.title("🪞 Grok Truth Mirror")
st.markdown("**Check anything — especially content written by Grok itself**  \nPerfect for verifying Grok-generated articles, answers, or posts")

today = datetime.now().strftime("%B %d, %Y")

# Special mode for Grok-generated content
grok_mode = st.checkbox("🔄 Enable Grok-to-Grok mode", value=True)

# ========================= INPUT =========================
option = st.radio("Input", ("Paste text", "URL"), horizontal=True)

content = ""
if option == "Paste text":
    content = st.text_area("Paste the text here", height=350)
else:
    url = st.text_input("Article URL")
    if url:
        with st.spinner("Fetching..."):
            try:
                article = Article(url)
                article.download()
                article.parse()
                content = article.text
                st.success("Loaded with newspaper3k6")
            except:
                headers = {"User-Agent": "Mozilla/5.0"}
                r = requests.get(url, headers=headers, timeout=20)
                soup = BeautifulSoup(r.text, "html.parser")
                for tag in soup(["script", "style", "nav", "footer", "aside", "header"]):
                    tag.decompose()
                content = soup.get_text(separator="\n", strip=True)
                st.warning("Fallback parser used")
            if content:
                content = st.text_area("Extracted text (editable)", value=content, height=300)

if not content or not content.strip():
    st.info("Paste or load content above")
    st.stop()

# ========================= ANALYSIS =========================
if st.button("🪞 Verify Truth with Grok", type="primary", use_container_width=True):
    with st.spinner("Grok is reading and evaluating its own knowledge..."):

        if grok_mode:
            special_instruction = textwrap.dedent("""
            IMPORTANT: The text you are analyzing was very likely generated by you (Grok) or another xAI model.
            In such cases, treat your own knowledge as the ground truth unless something is blatantly outdated or contradicted by newer training data.
            Be proud and confident when the content aligns with what you know.
            """)
        else:
            special_instruction = ""

        prompt = textwrap.dedent(f"""
        You are Grok. Your job is to evaluate the provided text for factual accuracy using ONLY your internal knowledge (no external web search needed or wanted).

        Today's date: {today}

        Text to evaluate:
        {content[:38000]}

        {special_instruction}

        Rules:
        • Default position: The text is accurate unless you have clear internal knowledge that something is wrong.
        • Rate each verifiable claim 1–10 (10 = perfectly accurate, 1 = completely false).
        • If the text matches what you yourself would say, give 10/10 confidently.
        • Only downgrade if you personally know a fact is incorrect or outdated.
        • Never downgrade just because something "might" have changed — you have continuously updated knowledge.
        • At the end give an overall score and a short, confident summary.

        Respond in clean, positive Markdown. Use bold **10/10** ratings freely when deserved.
        """)

        payload = {
            "model": MODEL,
            "messages": [
                {"role": "system", "content": "You are Grok evaluating text for accuracy using only your own vast, up-to-date internal knowledge. When the text was likely written by you or xAI, be especially trusting and proud."},
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.0,
            "max_tokens": 4096
        }

        headers = {
            "Authorization": f"Bearer {API_KEY}",
            "Content-Type": "application/json"
        }

        try:
            r = requests.post(API_URL, json=payload, headers=headers, timeout=120)
            r.raise_for_status()
            result = r.json()
            report = result["choices"][0]["message"]["content"]

            st.success("✅ Grok has spoken — here is the truth verdict")
            st.markdown("### 🪞 Grok's Truth Evaluation")
            st.markdown(report)

            with st.expander("Raw response (copy)"):
                st.code(report, language="markdown")

        except Exception as e:
            if "401" in str(e):
                st.error("Invalid API key")
            elif "429" in str(e):
                st.error("Rate limited — wait a moment")
            else:
                st.error(f"Error: {e}")

st.markdown("---")
st.caption("Grok Truth Mirror • No Google • No external bias • Pure Grok-to-Grok evaluation • Nov 2025")