import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.io as pio
import re
from datetime import datetime
import pdfkit
import os
from pathlib import Path

from hibp_client import get_breaches_for_email, get_all_breaches
from grok_analyzer import analyze_with_grok

# ==================== wkhtmltopdf Setup ====================
if os.name == "nt":
    possible_paths = [
        r"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe",
        r"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe",
    ]
    wk_path = next((p for p in possible_paths if Path(p).exists()), None)
    if not wk_path:
        st.error("wkhtmltopdf not found! Download from: https://wkhtmltopdf.org/downloads.html")
        st.stop()
else:
    wk_path = "wkhtmltopdf"

config = pdfkit.configuration(wkhtmltopdf=wk_path)

# ==================== Page Config (Icon Fixed) ====================
st.set_page_config(
    page_title="BreachWise",
    page_icon="🔒",
    layout="centered",
    initial_sidebar_state="expanded"
)

# ==================== Header ====================
st.markdown("<h1 style='text-align: center; font-size: 56px;'>BreachWise</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center; color: #888;'>Instant breach check + AI-powered risk analysis by HaveIBeenOwned + Grok xAI</p>", unsafe_allow_html=True)
st.markdown("---")

# ==================== Input ====================
email = st.text_input("Enter your email address", placeholder="you@example.com", label_visibility="collapsed")

col1, col2 = st.columns([3, 1])
with col1:
    check_btn = st.button("Check for Breaches", type="primary", width="stretch")
with col2:
    clear_btn = st.button("Clear Results", width="stretch")

if clear_btn:
    st.session_state.clear()
    st.rerun()

# ==================== PDF Report Generator ====================
def create_pdf_report(email: str, breaches, analysis: str):
    masked = email.split("@")[0][:3] + "***@" + email.split("@")[1]
    now = datetime.now().strftime("%B %d, %Y at %H:%M")

    if breaches:
        df = pd.DataFrame([{
            "Date": b["BreachDate"],
            "Breach": b["Title"],
            "Exposed": ", ".join(b["DataClasses"][:6])
        } for b in breaches])
        fig = px.timeline(df, x_start="Date", x_end="Date", y="Breach", text="Exposed",
                          title="Your Breach Timeline", color_discrete_sequence=["#d32f2f"])
        fig.update_yaxes(autorange="reversed")
        chart_svg = pio.to_image(fig, format="svg", scale=2)
        chart_img = f'<img src="data:image/svg+xml;base64,{chart_svg.decode()}" style="width:100%; max-width:900px;"/>'
    else:
        chart_img = "<p style='text-align:center; font-size:1.8em; color:#388e3c; margin:40px;'>No breaches found — you're all clear!</p>"

    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 50px; line-height: 1.6; }}
            h1 {{ color: #1565c0; text-align: center; }}
            .header {{ background: #0d47a1; color: white; padding: 25px; border-radius: 10px; text-align: center; }}
            .section {{ margin: 40px 0; }}
            .footer {{ margin-top: 100px; font-size: 0.9em; color: #666; text-align: center; }}
            pre {{ background: #f8f9fa; padding: 20px; border-radius: 8px; white-space: pre-wrap; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>BreachWise Security Report</h1>
            <p>Generated on {now}</p>
        </div>

        <h2>Email checked: {masked}</h2>
        <p><strong>Result:</strong> {'No breaches found' if not breaches else f'<strong style="color:#d32f2f;">Found in {len(breaches)} breach(es)</strong>'}</p>

        <div class="section">
            <h2>Your Breach Timeline</h2>
            <div style="text-align:center;">{chart_img}</div>
        </div>

        <div class="section">
            <h2>Grok AI Risk Assessment</h2>
            <pre>{analysis}</pre>
        </div>

        <div class="footer">
            <p>Report generated by BreachWise • Powered by haveibeenpwned.com & Grok xAI</p>
            <p>Take action today — your digital safety matters.</p>
        </div>
    </body>
    </html>
    """

    return pdfkit.from_string(html, False, configuration=config)

# ==================== Main Logic ====================
if check_btn:
    if not email or "@" not in email:
        st.error("Please enter a valid email address.")
    else:
        with st.spinner("Checking HaveIBeenPwned..."):
            breaches = get_breaches_for_email(email.strip().lower())
            st.session_state.breaches = breaches
            st.session_state.email = email

        st.markdown("---")

        if not breaches:
            st.balloons()
            st.success(f"**{email} is clean!** No breaches found.")
            analysis = analyze_with_grok([], email)
            st.info("### Grok says:\n" + analysis)
        else:
            st.error(f"Found in **{len(breaches)} data breach(es)**")

            df = pd.DataFrame([{
                "Date": b["BreachDate"],
                "Breach": b["Title"],
                "Exposed": ", ".join(b["DataClasses"][:6])
            } for b in breaches])
            df["Date"] = pd.to_datetime(df["Date"])
            fig = px.timeline(df.sort_values("Date"), x_start="Date", x_end="Date", y="Breach", text="Exposed",
                              title="Your Personal Breach Timeline", color_discrete_sequence=["#d32f2f"])
            fig.update_yaxes(autorange="reversed")
            st.plotly_chart(fig, width="stretch")

            with st.spinner("Grok is analyzing your personal risk..."):
                analysis = analyze_with_grok(breaches, email)

            st.markdown("### Grok's Personal Risk Assessment")
            st.markdown(analysis)

        with st.spinner("Generating your PDF report..."):
            pdf_bytes = create_pdf_report(email, breaches, analysis)
            st.download_button(
                label="Download My Breach Report (PDF)",
                data=pdf_bytes,
                file_name=f"BreachWise_Report_{datetime.now().strftime('%Y%m%d')}.pdf",
                mime="application/pdf",
                type="primary"
            )
        st.success("Your professional PDF report is ready!")

# ==================== Sidebar: Latest by Breach Date ====================
with st.sidebar:
    st.header("Latest Breaches Worldwide")
    st.caption("Most recent incidents by breach date")

    all_breaches = get_all_breaches()
    if all_breaches:
        valid = [b for b in all_breaches if b.get("BreachDate")]
        latest = sorted(valid, key=lambda x: x["BreachDate"], reverse=True)[:5]

        for b in latest:
            st.markdown(f"### {b['Title']}")
            st.caption(f"Breach Date: **{b['BreachDate']}**")
            st.caption(f"Added to HIBP: {b.get('AddedDate', 'N/A')[:10]}")
            st.caption(f"Accounts affected: {b['PwnCount']:,}")

            with st.expander("Details", expanded=False):
                clean = re.sub(r'<[^>]+>', '', b['Description'])
                clean = re.sub(r'\s+', ' ', clean).strip()
                st.markdown(clean)

                if b.get("DataClasses"):
                    st.markdown("**Data exposed:**")
                    cols = st.columns(4)
                    for i, item in enumerate(b["DataClasses"][:16]):
                        with cols[i % 4]:
                            st.markdown(f"`{item}`")
                    if len(b["DataClasses"]) > 16:
                        st.caption(f"+ {len(b['DataClasses'])-16} more")
            st.markdown("___")
    else:
        st.info("No breaches loaded (check rate limit)")

    st.markdown("---")
    st.markdown("Data: [haveibeenpwned.com](https://haveibeenpwned.com)")
    st.markdown("AI: **Grok xAI**")
    st.markdown("Made with love for your security")

# ==================== Footer ====================
st.caption("BreachWise • Zero logging • Open source • Powered by xAI & Troy Hunt")